Fix summarise trips without trips
asiripanich/emdash pull request #54
Opened 2021-07-23 03:19 UTC by allenmichael099

@asiripanich Shankari and I noticed today that there was an error with some of the trip summary columns. All participants had the same value. Also, the participation period plot was uniform. After looking into it, I realized that the mistake was in how I implemented summarise_trips_without_trips. It was using the min and max dates for all trips, rather than the min and max for each user. 

It seems to be fixed but perhaps it should be more carefully tested. I threw together the beginnings of a test that for it in test-utils_tidy_data, and the columns are mostly the same. One version seems to round the timestamps to the nearest day while the other does not. n_active_days might appear in a different order.

Here are relevant screenshots of the issue:
![Wrong_data_upload](https://user-images.githubusercontent.com/56986329/126733885-5458ff75-be6a-44d8-ab0f-f0f4337d6be4.PNG)
![Wrong_particip_pd](https://user-images.githubusercontent.com/56986329/126733887-37542d1c-a6ea-4d60-a3e3-f9c05aa9e0f4.PNG)

And after the fix:
![Fixed_data_upload](https://user-images.githubusercontent.com/56986329/126733911-7925bb69-5aa2-4fe3-b0b9-daf829792964.PNG)
![Fixed_Particip_Pd](https://user-images.githubusercontent.com/56986329/126733915-d311400d-be7c-4084-87d7-a9abdde01c0d.PNG)

2021-07-23 05:24 UTC, asiripanich commented
@allenmichael099 just wondering why did you comment that test out? c821219

2021-07-23 16:09 UTC, allenmichael099 commented
@asiripanich I figured it wasn't ready yet, and I didn't know what expectation to set.

2021-07-24 04:30 UTC, asiripanich commented
@allenmichael099 Could you please submit another PR with unit tests, after Aug is fine. Thanks!

2021-08-05 15:50 UTC, shankari requested changes
The code changes all make sense to me. Why is the test failing?

2021-08-05 15:50 UTC, shankari commented on R/utils_tidy_data.R
> +    .[is.na(unconfirmed), unconfirmed := 0]
Note to self: checked that this is the same as in my `master_specific_customization` branch

2021-08-05 15:50 UTC, shankari commented on R/utils_tidy_data.R
> +
note to self, this makes sense and is also similar to my original code.

2021-08-05 15:50 UTC, shankari commented on R/utils_tidy_data.R
> +      end_fmt_time = lubridate::as_datetime(trip_query$data.end_fmt_time) # convert trip end datetimes to UTC
note to self: this is similar to the original "before" code.

2021-08-05 15:50 UTC, shankari commented on R/utils_query_database.R
> +              "_id":false}', confirmed_user_input_column)
note to self: these fields seem fine and the `sprintf` makes sense. Thanks R for using standard C function name.

2021-08-05 15:50 UTC, shankari commented on R/utils_tidy_data.R
> +        as.character()
Ditto

2021-08-06 06:00 UTC, asiripanich commented
@allenmichael099  Now that we have `summarise_trips_without_trips()`, do we still need `summarise_trips()`

2021-08-06 06:36 UTC, merged

2021-08-09 14:48 UTC, allenmichael099 commented
@asiripanich I kept summarise_trips to test whether the output of summarise_trips_without_trips is different than it should be. It might still be useful to have summarise_trips to compare with the output from summarise_trips_without_trips after any future changes to summarise_trips_without_trips.

2021-08-09 14:55 UTC, asiripanich commented
> 
> 
> @asiripanich I kept summarise_trips to test whether the output of summarise_trips_without_trips is different than it should be. It might still be useful to have summarise_trips to compare with the output from summarise_trips_without_trips after any future changes to summarise_trips_without_trips.

That is what I thought you were trying to do. Instead of that, we can use `testthat` to take a snapshot of the output and test against that. See https://github.com/asiripanich/emdash/blob/master/tests/testthat/_snaps/utils_tidy_data.md.